
[lint]
select = ["ALL"]
ignore = [
    "D203",
    "D213",
]

exclude = [".venv", "__pycache__", "build", "dist", "*.bak"]

fixable = ["ALL"]

[lint.isort]
known-first-party = ["src"]
combine-as-imports = true
force-single-line = false

[lint.mccabe]
max-complexity = 10

[lint.flake8-quotes]
inline-quotes = "double"
multiline-quotes = "double"
avoid-escape = true

[lint.pycodestyle]
max-doc-length = 88
max-line-length = 88
